# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

welch_t_test <- function(x, y, mu = 0.0, alternative = "two.sided") {
    .Call(`_fastats_welch_t_test`, x, y, mu, alternative)
}

